
name: Push to Master
on:
  push:
    branches:
      - master

jobs:
  build-deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: echo "build"
      - name: deploy
        run: echo "tests"
 
  cypress-tests-stage:
    needs: build-deploy-stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Run Cypress Stage
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          config-file: cypress.stage.config.js
  
  build-deploy-prod:
    needs: cypress-tests-stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: echo "build"
      - name: deploy
        run: echo "deploy"
 
  cypress-tests-prod:
    needs: build-deploy-prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Run Cypress Prod
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          config-file: cypress.prod.config.js
 
 