
name: Push to Master
on:
  push:
    branches:
      - main

jobs:
  build-deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
  cypress-tests-stage:
    depends-on: build-deploy-stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Run Cypress Stage
          uses: cypress-io/github-action@v5
          with:
            browser: chrome
            config-file: cypress.stage.config.json
  
  build-deploy-prod:
    depends-on: cypress-tests-stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
  cypress-tests-prod:
    depends-on: build-deploy-prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Run Cypress Prod
          uses: cypress-io/github-action@v5
          with:
            browser: chrome
            config-file: cypress.prod.config.json
 
 