name: Cypress Tests Nightly Run - stage
on:
  schedule:
    - cron: '0 7 * * *' 
jobs:
 cypress-test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v5
       with:
         browser: chrome
         config-file: cypress.stage.config.js