
name: Cypress Tests on Prod on PR
on: pull_request
jobs:
  Cypress-Test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2
  
      - name: Run Cypress Prod
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          config-file: cypress.prod.config.json
